Feature/ratt
TriplyDB/Documentation pull request #6
Opened 2021-10-24 21:13 UTC by wouterbeek

This pull request includes the following changes:

- Small generic README file to explain what this repo is about.
- Generic pages for clean code, editors, environment variables, and API Tokens.
- Deduplicated content now in generic pages, resulting in cleanups in the TriplyDB.js and RATT documentation.
- Many small changes/additions for the TriplyDB.js documentation.
- Added most of the RATT documentation, based on sections that were previously published internally.
- I do not know how the changes to the 3 files related to blog posts got into this pull requests; these must have been introduced by others who committed before me in this feature branch.

2021-10-26 08:46 UTC, rosalinedehaan commented
I took out the 3 files related to the blog post. I commited those to the wrong branch a while back.

2021-10-28 08:19 UTC, evelienl commented on docs/ratt/index.md
> +**RATT is distributed under the TriplyDB license.  Contact [info@triply.cc](mailto:info@triply.cc) for more information.**
and should not be used separately from a TriplyDB licence or TriplyDB SaaS product.

2021-10-28 08:19 UTC, evelienl commented on docs/ratt/index.md
> +RATT is a [TypeScript package](https://www.npmjs.com/package/@triply/ratt) that is developed by Triply.  RATT makes it possible to develop and maintain production-grade linked data pipelines.  It is
knowledge graph without capitals

2021-10-28 08:22 UTC, MPvHarmelen commented on docs/ratt/index.md
> +</figure>
Why is this an HTML table and not a markdown table?

See [here](https://github.com/TriplyDB/Documentation/blob/master/docs/triply-db/index.md?plain=1#L617) for the syntax. Maybe we should also add that we support markdown tables to the documentation that I linked.

2021-10-28 08:23 UTC, MPvHarmelen commented on docs/ratt/index.md
> +<h3 id="change">Change an existing entry in-place (<code>change</code>)</h3>
Same here, why is this HTML?

2021-10-28 08:25 UTC, MPvHarmelen commented on docs/ratt/index.md
> +    change: value => FUNCTION_BODY}),
In the dev-team we consider it bad style not to have parentheses around the arguments of an arrow function, i.e. I would suggest `(value) => FUNCTION_BOYD`.

2021-10-28 08:27 UTC, simonwtriply commented on docs/ratt/index.md
> +The `mw.when` function supports the creation of triples under certain conditions.  The first argument that this function takes establishes whether or not a certain condition is met.  After that one o
"After that, one or more..." (add comma)

2021-10-28 08:28 UTC, MPvHarmelen commented on docs/ratt/index.md
> +  - `'any'` an undetermined type.
Do we support that in RATT? And are we not documenting `unknown`?

2021-10-28 08:30 UTC, MPvHarmelen commented on docs/ratt/index.md
> +- `FUNCTION_BODY` the body of a function, ending with a `return` statement that returns the new value.
This is not strictly speaking correct. In Typescript, you can have a shorthand arrow-function if the function would only have been a single return statement:

```ts
(ARGUMENTS) => EXPRESSION
```

is short for

```ts
(ARGUMENTS) => {
  return EXPRESSION
}
```

and arguably more readable.

2021-10-28 08:42 UTC, evelienl commented on docs/ratt/index.md
> +RATT supports the official CSV standard: [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180).  Unfortunately, there are some ‘CSV’ files our there that do not follow the RFC 4180 standard.  Str
'our there' -> 'out there'

2021-10-28 08:50 UTC, simonwtriply commented on docs/ratt/index.md
> +Example of using the `--verbose` flag:
"Example" doesn't start on a new line.

2021-10-28 08:54 UTC, MPvHarmelen requested changes
See also my changes in c1ff06bc67c4458d6bbfa00d5052cbd570f6a871

2021-10-28 08:54 UTC, MPvHarmelen commented on docs/ratt/index.md
> +  change: value => value.padStart(4, '0'),
We use the shorthand arrow-function notation here, so I do think we should document it (see comment above).

Again: `(value)` instead of `value`, to make it more explicit that we're introducing a new variable here, instead of using the value of an existing one?

2021-10-28 08:54 UTC, MPvHarmelen commented on docs/ratt/index.md
> +  change: value => value as number / 1}),
Why not `+(value as number)`? Division may do weird stuff? Floats scare me.

2021-10-28 08:54 UTC, MPvHarmelen commented on docs/ratt/index.md
> +| France      | null        |
If I try this in Node.js v14.18.1 the following happens:

```node
> '' / 1
0
> +''
0
```

Thus documenting the resulting value as `null` is incorrect.

2021-10-28 08:54 UTC, MPvHarmelen commented on docs/ratt/index.md
> +  key: keys.country_of_birth,
`keys.country_of_birth` isn't explained anywhere. Should this be replaced by `'Source value'`?

2021-10-31 16:19 UTC, wouterbeek commented on docs/ratt/index.md
> +RATT is a [TypeScript package](https://www.npmjs.com/package/@triply/ratt) that is developed by Triply.  RATT makes it possible to develop and maintain production-grade linked data pipelines.  It is
changed

2021-10-31 16:19 UTC, wouterbeek commented on docs/ratt/index.md
> +**RATT is distributed under the TriplyDB license.  Contact [info@triply.cc](mailto:info@triply.cc) for more information.**
Adding this to the Management Team agenda.

2021-10-31 16:32 UTC, wouterbeek commented on docs/ratt/index.md
> +</figure>
Sorry, this is just too much work for me.  We need some documentation online.

2021-10-31 16:33 UTC, wouterbeek commented on docs/ratt/index.md
> +<h3 id="change">Change an existing entry in-place (<code>change</code>)</h3>
I have to refer to that section.  I do not know which ID is generated by Markdown.  I cannot test this locally.  Sorry.

2021-10-31 16:35 UTC, wouterbeek commented on docs/ratt/index.md
> +The `mw.when` function supports the creation of triples under certain conditions.  The first argument that this function takes establishes whether or not a certain condition is met.  After that one o
Changed.

2021-10-31 16:36 UTC, wouterbeek commented on docs/ratt/index.md
> +  - `'any'` an undetermined type.
I don't know what this means.  I have not seen `unknown` yet.

2021-10-31 16:38 UTC, wouterbeek commented on docs/ratt/index.md
> +  - `'any'` an undetermined type.
I hope somebody else will be able to fix this later.

2021-10-31 16:39 UTC, wouterbeek commented on docs/ratt/index.md
> +    change: value => FUNCTION_BODY}),
I'm looking into why brackets could be better and may change this later.

2021-10-31 16:46 UTC, wouterbeek commented on docs/ratt/index.md
> +- `FUNCTION_BODY` the body of a function, ending with a `return` statement that returns the new value.
I know very little about TS.  I have changed this into:
> - `FUNCTION_BODY` a function body that returns the new value.
But I have no idea whether this is more correct.

2021-10-31 16:46 UTC, wouterbeek commented on docs/ratt/index.md
> +RATT supports the official CSV standard: [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180).  Unfortunately, there are some ‘CSV’ files our there that do not follow the RFC 4180 standard.  Str
fixed

2021-10-31 16:47 UTC, wouterbeek commented on docs/ratt/index.md
> +Example of using the `--verbose` flag:
I do not understand what this means.  I have rewritten that sentence to:

> The following example shows how the `--verbose` flag can be used:

I hope this fixes the issue that you saw.

2021-10-31 16:49 UTC, wouterbeek commented on docs/ratt/index.md
> +  change: value => value.padStart(4, '0'),
I do not understand this comment.  Let's fix this later.

2021-10-31 16:57 UTC, wouterbeek commented on docs/ratt/index.md
> +| France      | null        |
Good catch!

2021-10-31 17:20 UTC, wouterbeek commented on docs/ratt/index.md
> +| France      | null        |
Very strange: the empty strings is treated differently from other strings that do not encode a number.  I have adding this odd exception to the documentation and have also asked a question about this in the RATT chat channel.

2021-10-31 17:21 UTC, wouterbeek commented on docs/ratt/index.md
> +  key: keys.country_of_birth,
Good catch!  changed.

2021-10-31 17:22 UTC, wouterbeek commented on docs/ratt/index.md
> +  change: value => value as number / 1}),
I have never seen either `+` or `/` to cast a value.  Either way looks completely crazy to me, but happy to change to `+`.

2021-10-31 17:31 UTC, wouterbeek reviewed
LGTM

2021-10-31 17:34 UTC, wouterbeek reviewed
LGTM

2021-11-01 07:42 UTC, wouterbeek commented
I cannot finish this pull request because I lack knowledge of Git/Github.  I hope somebody else can take over of do this together with me.

2021-11-01 09:24 UTC, MPvHarmelen approved these changes

2021-11-01 12:52 UTC, TanjaRonzhina commented
Double checked the documentation. 
LGTM!
Only the broken links should be updated:
1. in section [External prefixes](https://github.com/TriplyDB/Documentation/blob/feature/ratt/docs/ratt/index.md#external-prefixes) [the link](https://github.com/TriplyDB/Documentation/blob/feature/ratt/docs/generics/editor) in the sentence "In properly configured text editors this will bring up a list of autocomplete results" doesn't work
2. in section [Publish to TriplyDB](https://github.com/TriplyDB/Documentation/blob/feature/ratt/docs/ratt/index.md#publish-to-triplydb) link [how to configure API token](https://github.com/TriplyDB/Documentation/blob/feature/ratt/docs/generics/api-token) doesn't work
3. in section [verbose mode](https://github.com/TriplyDB/Documentation/blob/feature/ratt/docs/ratt/index.md#verbose-mode) link to [environment variables](https://github.com/TriplyDB/Documentation/blob/feature/ratt/docs/generics/environment-variable) also ends with 404 error

2021-11-02 07:15 UTC, merged